#!/bin/sh
# Copyright 2005 Josef Schmeisser
# Distributed under the terms of the GNU General Public License v2

PATH=/bin:/sbin:/usr/sbin
NAME="storm-ircd"
DESC="ircd"

case "$1" in
  start)
    echo -n "Starting $DESC: "
    storm-ircd
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    storm-ircd -n
    echo "$NAME."
    ;;
  restart)
    echo -n "Restarting $DESC: "
    storm-ircd -n
    sleep 1
    storm-ircd
    echo "$NAME."
    ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart}" >&2
    exit 1
    ;;
esac
